source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-relative-links", "~> 0.7"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-include-cache", "~> 0.2"
gem "webrick", "~> 1.8"
